### ISSUE TITLE
Localized Labs Using Old Instructions

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer.ko-kr#1]
Although the link below is to an Issue I filed in the Simplified Chinese localized repo for AZ-220 some time ago, this issue is still present there...and also here.

https://github.com/MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer.zh-cn/issues/2

Will this be updated soon to the new AZ-220 revision as is present in AZ-220/English repo?

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by olprod** [comment]
https://github.com/MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer.ko-kr/tree/OLPRODLOC  
New version updated.
